apiVersion: v1
kind: Service
metadata:
  name: obras-service
  labels:
    app: obras
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: obras
    tier: backend

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: obras
spec:
  selector:
    matchLabels:
      app: obras
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: obras
        tier: backend
    spec:
      containers:
      - name: obras
        imagePullPolicy: IfNotPresent
        image: martinsaporiti/obras_catalog_service:1.0.0
        ports:
          - name: http
            containerPort: 5000