apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: obras-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /obras
        backend:
          serviceName: obras-service
          servicePort: 80