apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ratings-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /ratings
        backend:
          serviceName: ratings-service
          servicePort: 80